export default {"1": {"symbol": "HREG_T_OP1", "multiplier": 10, "title": "Room temperature sensor TE20"}, 
"2": {"symbol": "HREG_T_OP2", "multiplier": 10, "title": "Room temperature sensor TE21"}, 
"3": {"symbol": "HREG_EFFECTIVE_TF", "multiplier": 1, "title": "Current supply fan speed"}, 
"4": {"symbol": "HREG_EFFECTIVE_PF", "multiplier": 1, "title": "Current exhaust fan speed"}, 
"5": {"symbol": "HREG_UPCOMING_TIME_PROGRAM", "multiplier": 1, "title": "Next time program"}, 
"6": {"symbol": "HREG_T_FRS", "multiplier": 10, "title": "Fresh air"}, 
"7": {"symbol": "HREG_T_SPLY_LTO", "multiplier": 10, "title": "Supply air after HRC"}, 
"8": {"symbol": "HREG_T_SPLY", "multiplier": 10, "title": "Supply air"}, 
"9": {"symbol": "HREG_T_WST", "multiplier": 10, "title": "Waste air"}, 
"10": {"symbol": "HREG_T_EXT", "multiplier": 10, "title": "Room removed air"}, 
"11": {"symbol": "HREG_T_EXT_LTO", "multiplier": 10, "title": "Removed air before HRC"}, 
"12": {"symbol": "HREG_T_WR", "multiplier": 10, "title": "Return water"}, 
"13": {"symbol": "HREG_HUM_EXT", "multiplier": 1, "title": "Exhaust air humidity"}, 
"14": {"symbol": "HREG_PRES_SPLYF", "multiplier": 1, "title": "Pressure difference supply"}, 
"15": {"symbol": "HREG_PRES_EXTF", "multiplier": 1, "title": "Pressure difference ext"}, 
"16": {"symbol": "HREG_TE07", "multiplier": 10, "title": "HP/MDX/Dehum supply air"}, 
"17": {"symbol": "HREG_AI1", "multiplier": 10, "title": "Analog input voltage"}, 
"18": {"symbol": "HREG_AI2", "multiplier": 10, "title": "Analog input voltage"}, 
"19": {"symbol": "HREG_AI3", "multiplier": 10, "title": "Analog input voltage"}, 
"20": {"symbol": "HREG_AI4", "multiplier": 10, "title": "Analog input voltage"}, 
"21": {"symbol": "HREG_AI5", "multiplier": 10, "title": "Analog input voltage"}, 
"22": {"symbol": "HREG_AI6", "multiplier": 10, "title": "Analog input voltage"}, 
"23": {"symbol": "HREG_AI1_RES", "multiplier": 1, "title": "Calculated value"}, 
"24": {"symbol": "HREG_AI2_RES", "multiplier": 1, "title": "Calculated value"}, 
"25": {"symbol": "HREG_AI3_RES", "multiplier": 1, "title": "Calculated value"}, 
"26": {"symbol": "HREG_AI4_RES", "multiplier": 1, "title": "Calculated value"}, 
"27": {"symbol": "HREG_AI5_RES", "multiplier": 1, "title": "Calculated value"}, 
"28": {"symbol": "HREG_AI6_RES", "multiplier": 1, "title": "Calculated value"}, 
"29": {"symbol": "HREG_LTO_N_SPLY", "multiplier": 1, "title": "Heat recovery efficiency n supply"}, 
"30": {"symbol": "HREG_LTO_N_EXT", "multiplier": 1, "title": "Heat recovery efficiency n exhaust"}, 
"31": {"symbol": "HREG_NTC_X6", "multiplier": 10, "title": "Input X6"}, 
"32": {"symbol": "HREG_NTC_X7", "multiplier": 10, "title": "Input X7"}, 
"33": {"symbol": "HREG_ABS_HUM_CTRL_OUTPUT", "multiplier": 1, "title": "Absolute humidity control output"}, 
"34": {"symbol": "HREG_NWK_STATUS", "multiplier": 1, "title": "Network status"}, 
"35": {"symbol": "HREG_RH_MEAN", "multiplier": 1, "title": "48h air humidity average"}, 
"36": {"symbol": "HREG_ABSHUM10", "multiplier": 10, "title": "Supply air absolute humidity"}, 
"37": {"symbol": "HREG_SEC_RTC", "multiplier": 1, "title": "s"}, 
"38": {"symbol": "HREG_MIN_RTC", "multiplier": 1, "title": "min"}, 
"39": {"symbol": "HREG_HOUR_RTC", "multiplier": 1, "title": "h"}, 
"40": {"symbol": "HREG_DAY_RTC", "multiplier": 1, "title": ""}, 
"41": {"symbol": "HREG_MONTH_RTC", "multiplier": 1, "title": ""}, 
"42": {"symbol": "HREG_YEAR_RTC", "multiplier": 1, "title": ""}, 
"44": {"symbol": "HREG_MODE", "multiplier": 1, "title": "Status"}, 
"45": {"symbol": "HREG_EXTMODE", "multiplier": 1, "title": "Temperature control step"}, 
"46": {"symbol": "HREG_ROOM_TEMP", "multiplier": 10, "title": "Room temperature average"}, 
"47": {"symbol": "HREG_CASCADE_SP", "multiplier": 10, "title": "Setpoint for supply air"}, 
"48": {"symbol": "HREG_DISPLAY_SP", "multiplier": 10, "title": ""}, 
"49": {"symbol": "HREG_OUTPUT", "multiplier": 1, "title": "Controller output"}, 
"104": {"symbol": "HREG_AI1_TYPE", "multiplier": 1, "title": "Sensor type"}, 
"105": {"symbol": "HREG_AI2_TYPE", "multiplier": 1, "title": "Sensor type"}, 
"106": {"symbol": "HREG_AI3_TYPE", "multiplier": 1, "title": "Sensor type"}, 
"107": {"symbol": "HREG_AI4_TYPE", "multiplier": 1, "title": "Sensor type"}, 
"108": {"symbol": "HREG_AI5_TYPE", "multiplier": 1, "title": "Sensor type"}, 
"109": {"symbol": "HREG_AI6_TYPE", "multiplier": 1, "title": "Sensor type"}, 
"110": {"symbol": "HREG_AI1_VL", "multiplier": 10, "title": "Voltage low"}, 
"111": {"symbol": "HREG_AI2_VL", "multiplier": 10, "title": "Voltage low"}, 
"112": {"symbol": "HREG_AI3_VL", "multiplier": 10, "title": "Voltage low"}, 
"113": {"symbol": "HREG_AI4_VL", "multiplier": 10, "title": "Voltage low"}, 
"114": {"symbol": "HREG_AI5_VL", "multiplier": 10, "title": "Voltage low"}, 
"115": {"symbol": "HREG_AI6_VL", "multiplier": 10, "title": "Voltage low"}, 
"116": {"symbol": "HREG_AI1_VH", "multiplier": 10, "title": "Voltage high"}, 
"117": {"symbol": "HREG_AI2_VH", "multiplier": 10, "title": "Voltage high"}, 
"118": {"symbol": "HREG_AI3_VH", "multiplier": 10, "title": "Voltage high"}, 
"119": {"symbol": "HREG_AI4_VH", "multiplier": 10, "title": "Voltage high"}, 
"120": {"symbol": "HREG_AI5_VH", "multiplier": 10, "title": "Voltage high"}, 
"121": {"symbol": "HREG_AI6_VH", "multiplier": 10, "title": "Voltage high"}, 
"122": {"symbol": "HREG_AI1_RL", "multiplier": 1, "title": "Result low"}, 
"123": {"symbol": "HREG_AI2_RL", "multiplier": 1, "title": "Result low"}, 
"124": {"symbol": "HREG_AI3_RL", "multiplier": 1, "title": "Result low"}, 
"125": {"symbol": "HREG_AI4_RL", "multiplier": 1, "title": "Result low"}, 
"126": {"symbol": "HREG_AI5_RL", "multiplier": 1, "title": "Result low"}, 
"127": {"symbol": "HREG_AI6_RL", "multiplier": 1, "title": "Result low"}, 
"128": {"symbol": "HREG_AI1_RH", "multiplier": 1, "title": "Result high"}, 
"129": {"symbol": "HREG_AI2_RH", "multiplier": 1, "title": "Result high"}, 
"130": {"symbol": "HREG_AI3_RH", "multiplier": 1, "title": "Result high"}, 
"131": {"symbol": "HREG_AI4_RH", "multiplier": 1, "title": "Result high"}, 
"132": {"symbol": "HREG_AI5_RH", "multiplier": 1, "title": "Result high"}, 
"133": {"symbol": "HREG_AI6_RH", "multiplier": 1, "title": "Result high"}, 
"134": {"symbol": "HREG_TE01_24H_AVG", "multiplier": 10, "title": "Average outside temperature"}, 
"135": {"symbol": "HREG_T_SETPOINT", "multiplier": 10, "title": "Supply air setpoint"}, 
"137": {"symbol": "HREG_TE01_SUMMER_WINTER_THRESHOLD", "multiplier": 10, "title": "Summer/Winter threshold"}, 
"172": {"symbol": "HREG_TEMP_DECREASE_VAL", "multiplier": 10, "title": "Temperature decrease"}, 
"210": {"symbol": "HREG_DAY_WC1", "multiplier": 1, "title": "Week timer slot #1"}, 
"211": {"symbol": "HREG_STA_HOUR_WC1", "multiplier": 1, "title": ""}, 
"212": {"symbol": "HREG_STA_MIN_WC1", "multiplier": 1, "title": ""}, 
"213": {"symbol": "HREG_STO_HOUR_WC1", "multiplier": 1, "title": ""}, 
"214": {"symbol": "HREG_STO_MIN_WC1", "multiplier": 1, "title": ""}, 
"215": {"symbol": "HREG_WC1", "multiplier": 1, "title": ""}, 
"216": {"symbol": "HREG_DAY_WC2", "multiplier": 1, "title": "Week timer slot #2"}, 
"217": {"symbol": "HREG_STA_HOUR_WC2", "multiplier": 1, "title": ""}, 
"218": {"symbol": "HREG_STA_MIN_WC2", "multiplier": 1, "title": ""}, 
"219": {"symbol": "HREG_STO_HOUR_WC2", "multiplier": 1, "title": ""}, 
"220": {"symbol": "HREG_STO_MIN_WC2", "multiplier": 1, "title": ""}, 
"221": {"symbol": "HREG_WC2", "multiplier": 1, "title": ""}, 
"222": {"symbol": "HREG_DAY_WC3", "multiplier": 1, "title": "Week timer slot #3"}, 
"223": {"symbol": "HREG_STA_HOUR_WC3", "multiplier": 1, "title": ""}, 
"224": {"symbol": "HREG_STA_MIN_WC3", "multiplier": 1, "title": ""}, 
"225": {"symbol": "HREG_STO_HOUR_WC3", "multiplier": 1, "title": ""}, 
"226": {"symbol": "HREG_STO_MIN_WC3", "multiplier": 1, "title": ""}, 
"227": {"symbol": "HREG_WC3", "multiplier": 1, "title": ""}, 
"228": {"symbol": "HREG_DAY_WC4", "multiplier": 1, "title": "Week timer slot #4"}, 
"229": {"symbol": "HREG_STA_HOUR_WC4", "multiplier": 1, "title": ""}, 
"230": {"symbol": "HREG_STA_MIN_WC4", "multiplier": 1, "title": ""}, 
"231": {"symbol": "HREG_STO_HOUR_WC4", "multiplier": 1, "title": ""}
}